# Generated by Django 4.2.11 on 2024-12-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('director_name', models.CharField(max_length=30)),
                ('publication_year', models.DateField()),
                ('synopsis', models.CharField(max_length=150)),
            ],
        ),
    ]
